### PR TITLE
Updated composer json and readme

### PR DESCRIPTION
**Pull request by pinclau**
#5

### CODE REVIEW

**Review by arhimede — COMMENTED** [review]
why 7.3 ?
line 19 in composer.json 
^7.3

**Comment by pinclau** [comment]
> why 7.3 ? line 19 in composer.json ^7.3

typo error. fixed in the latest commit

**Review by arhimede — CHANGES_REQUESTED** [review]
readme.md , line 6
dot-authorization/3.2.0   to reflect the new future release

**Review by arhimede — CHANGES_REQUESTED** [review]
composer.json
"laminas/laminas-dependency-plugin": "^2.2" which is the latest

**Review by arhimede — APPROVED** [review]

**Pull request merged**
